### ISSUE TITLE
负载均衡的申请和配置

### ISSUE THREAD

**Issue by xiangpingjiang** [vinkdong/kubernetes-the-hard-way-cn#1]
您好，  https://github.com/vinkdong/kubernetes-the-hard-way-cn/blob/master/docs/04-certificate-authority.md#%E7%94%9F%E6%88%90apiserver%E7%9A%84%E8%AF%81%E4%B9%A6  生成ApiServer的证书
，  这里提到的负载均衡是如何申请配置的？

感谢。

**Comment by vinkdong** [comment]
负载均衡可以是公有云的SLB或者F5，也可以是nginx或者haproxy这个看个人需求，这里只是为了将负载均衡的IP加到证书里面，确保使用这个IP可以正常通过证书校验。如果是在主机上搭的负载均衡就不用添加。
